version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
  php:
    image: php:8.2-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "4001:80"
    volumes:
      - ./app:/var/www/html
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - frontend
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

volumes:
  mysql_data:
